import Head from 'next/head';
import Header from '@/components/Header';
import Brand from '@/components/Brand';
import CardEvent from '@/components/CardEvent';
import { getData } from '@/utils/fetchData';

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Semina | Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Brand />
      <CardEvent data={data} title="Featured Events" subTitle="Grow Today" />
    </>
  );
}

export async function getServerSideProps(context) {
  const req = await getData('api/v1/events');
  const res = req.data;

  return {
    props: { data: res },
  };
}
