import Head from 'next/head';
import Header from '@/components/Header';
import Brand from '@/components/Brand';

export default function Home() {
  return (
    <>
      <Head>
        <title>Semina | Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Brand />
    </>
  );
}
